version: 2

# Project-specific information
build:
  image: "ubuntu-20.04"  # Use an Ubuntu image for building
  tools:
    python: "3.9"  # Python version

# Define which directory to use as the source of your docs
sphinx:
  configuration: docs/conf.py  # Path to your Sphinx conf.py file (if using Sphinx)

mkdocs:
  configuration: mkdocs.yml  # Path to your MkDocs configuration file
  clean: true  # Clean the site directory before building

# Additional build steps if needed (e.g., installing dependencies)
install:
  - requirements: "requirements.txt"  # Install dependencies from requirements.txt

# Define the default branch to build from
branches:
  - main  # Replace with your default branch name if different
