version: 2

# Define the build image
build:
  image: "ubuntu-20.04"  # Correct image name, no need for an `os` field

# Define the documentation builder
mkdocs:
  configuration: mkdocs.yml  # Path to your MkDocs configuration file
  clean: true  # Clean the site directory before building

# Install dependencies (optional, if you have a requirements.txt)
install:
  - requirements: "requirements.txt"

# Define the branches to be built
branches:
  - main  # Replace with your default branch name if different
