theme: jekyll-theme-slate

navigation:
  - text: Introduction
    internal: true
    url: ./
  - text: Installation
    internal: true
    url: installation
  - text: Usage
    internal: true
    url: usage
  - text: Error Handling
    internal: true
    url: error_handling
  - text: Views & ViewSets
    internal: true
    url: views_viewsets
  - text: API Reference
    internal: true
    url: api_reference
  - text: Changelog
    internal: true
    url: changelog
  - text: GitHub Setup
    internal: true
    url: github
  - text: Edit this Repo
    internal: false
    url: https://github.com/QuvonchbekBobojonov/django-success-response
