# _config.yml for django-success-response documentation

# Basic site settings
title: "django-success-response Documentation"
description: "Standardized success and error response handling for Django REST Framework."
url: "http://django-success-response.moorfo.uz/"
baseurl: ""
author: "Quvonchbek Bobojonov"
github: "https://github.com/QuvonchbekBobojonov/django-success-response"
repository: "https://github.com/QuvonchbekBobojonov/django-success-response"
version: "1.0.0"

# Navigation settings
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Error Handling: error_handling.md
  - Views & ViewSets: views_viewsets.md
  - API Reference: api_reference.md
  - Changelog: changelog.md

# Configure theme
theme:
  name: "jekyll-theme-cayman"
  remote_theme: "pages-themes/cayman@v0.2.0"
  repo: "your-username/django-success-response"
  color_scheme: "light"
  font: "Arial, sans-serif"

# Build settings
markdown: kramdown
highlighter: rouge
exclude:
  - "README.md"
  - "Gemfile"
  - "Gemfile.lock"

# Author and contact settings
author_name: "Quvonchbek Bobojonov"
author_email: "hi@moorfo.uz"
author_link: "https://moorfo.uz/"
contact_email: "contact@moorfo.uz"

# Plugin settings (if any)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Markdown options
markdown_ext: .md
