# Basic site settings
title: "django-success-response Documentation"
description: "Standardized success and error response handling for Django REST Framework."
url: "http://django-success-response.moorfo.uz/"  # The URL for the site
baseurl: ""  # Keep this blank if it's hosted at the root of the domain
author: "Quvonchbek Bobojonov"
github: "https://github.com/QuvonchbekBobojonov/django-success-response"  # GitHub repository link
repository: "https://github.com/QuvonchbekBobojonov/django-success-response"  # GitHub repository link
version: "1.0.0"  # Version of the package

# Navigation settings
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Error Handling: error_handling.md
  - Views & ViewSets: views_viewsets.md
  - API Reference: api_reference.md
  - Changelog: changelog.md

# Configure theme
theme:
  name: "jekyll-theme-cayman"  # Choose a theme; Jekyll's Cayman is a simple and elegant choice
  remote_theme: pages-themes/minimal@v0.2.0  # Another theme option for minimal design
  repo: "QuvonchbekBobojonov/django-success-response"  # GitHub repository link for theme
  color_scheme: "light"  # Light color scheme
  font: "Arial, sans-serif"  # Standard font

# Build settings
markdown: kramdown  # Markdown processor
highlighter: rouge  # Syntax highlighting for code blocks
exclude:
  - "README.md"  # Exclude certain files from the build
  - "Gemfile"
  - "Gemfile.lock"

# Author and contact settings
author_name: "Quvonchbek Bobojonov"
author_email: "hi@moorfo.uz"  # Author's email for contact
author_link: "https://moorfo.uz/"  # Author's website link
contact_email: "contact@moorfo.uz"  # Contact email for inquiries

# Plugin settings (if any)
plugins:
  - jekyll-remote-theme  # Plugin to use a remote theme if necessary

# Markdown options
markdown_ext: .md  # Only process markdown files
